// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(ViajeContext))]
    [Migration("20230703194731_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Pasajero", b =>
                {
                    b.Property<int>("PasajeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PasajeroId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumContactoEmergencia")
                        .HasColumnType("int");

                    b.Property<int>("ViajeId")
                        .HasColumnType("int");

                    b.HasKey("PasajeroId");

                    b.HasIndex("ViajeId");

                    b.ToTable("Pasajero", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Viaje", b =>
                {
                    b.Property<int>("ViajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViajeId"));

                    b.Property<int>("AsientosDisponibles")
                        .HasColumnType("int");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaLlegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("TipoViaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransporteId")
                        .HasColumnType("int");

                    b.HasKey("ViajeId");

                    b.ToTable("Viaje", (string)null);

                    b.HasData(
                        new
                        {
                            ViajeId = 1,
                            AsientosDisponibles = 45,
                            Duracion = "8 Horas",
                            FechaLlegada = new DateTime(2023, 10, 5, 5, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 10, 12, 5, 0, 0, 514, DateTimeKind.Local),
                            Precio = 15000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 34
                        },
                        new
                        {
                            ViajeId = 2,
                            AsientosDisponibles = 200,
                            Duracion = "8 Horas",
                            FechaLlegada = new DateTime(2023, 11, 30, 17, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 11, 15, 19, 0, 0, 514, DateTimeKind.Local),
                            Precio = 12000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 35
                        },
                        new
                        {
                            ViajeId = 3,
                            AsientosDisponibles = 300,
                            Duracion = "18 Horas",
                            FechaLlegada = new DateTime(2024, 7, 18, 7, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2024, 7, 1, 17, 0, 0, 514, DateTimeKind.Local),
                            Precio = 650000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 4
                        },
                        new
                        {
                            ViajeId = 4,
                            AsientosDisponibles = 350,
                            Duracion = "30 horas",
                            FechaLlegada = new DateTime(2024, 6, 7, 19, 30, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2024, 6, 1, 7, 30, 0, 514, DateTimeKind.Local),
                            Precio = 1250000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 5
                        },
                        new
                        {
                            ViajeId = 5,
                            AsientosDisponibles = 123,
                            Duracion = "2 horas",
                            FechaLlegada = new DateTime(2023, 12, 10, 5, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 12, 3, 3, 0, 0, 514, DateTimeKind.Local),
                            Precio = 27000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 6
                        },
                        new
                        {
                            ViajeId = 6,
                            AsientosDisponibles = 250,
                            Duracion = "3 Horas 30 min",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 7, 10, 7, 30, 0, 514, DateTimeKind.Local),
                            Precio = 23000,
                            TipoViaje = "Ida",
                            TransporteId = 7
                        },
                        new
                        {
                            ViajeId = 7,
                            AsientosDisponibles = 165,
                            Duracion = "4 Horas",
                            FechaLlegada = new DateTime(2023, 8, 8, 7, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 8, 1, 3, 0, 0, 514, DateTimeKind.Local),
                            Precio = 30000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 8
                        },
                        new
                        {
                            ViajeId = 8,
                            AsientosDisponibles = 80,
                            Duracion = "1 Hora(s)",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 7, 15, 13, 0, 0, 514, DateTimeKind.Local),
                            Precio = 30500,
                            TipoViaje = "Ida",
                            TransporteId = 12
                        },
                        new
                        {
                            ViajeId = 9,
                            AsientosDisponibles = 225,
                            Duracion = "1 Hora",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 7, 5, 8, 30, 0, 514, DateTimeKind.Local),
                            Precio = 35000,
                            TipoViaje = "Ida",
                            TransporteId = 8
                        },
                        new
                        {
                            ViajeId = 10,
                            AsientosDisponibles = 350,
                            Duracion = "1 Hora 30 min",
                            FechaLlegada = new DateTime(2023, 7, 21, 6, 15, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 7, 15, 3, 15, 0, 514, DateTimeKind.Local),
                            Precio = 41050,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 9
                        },
                        new
                        {
                            ViajeId = 11,
                            AsientosDisponibles = 300,
                            Duracion = "3 Horas",
                            FechaLlegada = new DateTime(2024, 1, 21, 12, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2024, 1, 3, 15, 0, 0, 514, DateTimeKind.Local),
                            Precio = 70250,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 10
                        },
                        new
                        {
                            ViajeId = 12,
                            AsientosDisponibles = 111,
                            Duracion = "17 Horas",
                            FechaLlegada = new DateTime(2023, 10, 23, 17, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 10, 16, 12, 0, 0, 514, DateTimeKind.Local),
                            Precio = 350000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 11
                        },
                        new
                        {
                            ViajeId = 13,
                            AsientosDisponibles = 325,
                            Duracion = "14 Hora(s)",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 7, 7, 3, 0, 0, 514, DateTimeKind.Local),
                            Precio = 380000,
                            TipoViaje = "Ida",
                            TransporteId = 13
                        },
                        new
                        {
                            ViajeId = 14,
                            AsientosDisponibles = 172,
                            Duracion = "17 Hora(s)",
                            FechaLlegada = new DateTime(2023, 12, 13, 14, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 11, 28, 9, 0, 0, 514, DateTimeKind.Local),
                            Precio = 638000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 14
                        },
                        new
                        {
                            ViajeId = 15,
                            AsientosDisponibles = 210,
                            Duracion = "3 Hora(s)",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 7, 7, 13, 0, 0, 514, DateTimeKind.Local),
                            Precio = 68000,
                            TipoViaje = "Ida",
                            TransporteId = 15
                        },
                        new
                        {
                            ViajeId = 16,
                            AsientosDisponibles = 190,
                            Duracion = "5 Hora(s)",
                            FechaLlegada = new DateTime(2023, 9, 4, 5, 30, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 9, 1, 3, 30, 0, 514, DateTimeKind.Local),
                            Precio = 80000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 16
                        },
                        new
                        {
                            ViajeId = 17,
                            AsientosDisponibles = 85,
                            Duracion = "19 Horas",
                            FechaLlegada = new DateTime(2023, 8, 30, 12, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 8, 25, 4, 0, 0, 514, DateTimeKind.Local),
                            Precio = 35000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 22
                        },
                        new
                        {
                            ViajeId = 18,
                            AsientosDisponibles = 250,
                            Duracion = "2 Horas 30 min",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 11, 8, 11, 30, 0, 514, DateTimeKind.Local),
                            Precio = 54500,
                            TipoViaje = "Ida",
                            TransporteId = 17
                        },
                        new
                        {
                            ViajeId = 19,
                            AsientosDisponibles = 100,
                            Duracion = "20 Horas",
                            FechaLlegada = new DateTime(2023, 10, 23, 17, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 10, 16, 12, 0, 0, 514, DateTimeKind.Local),
                            Precio = 618000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 18
                        },
                        new
                        {
                            ViajeId = 20,
                            AsientosDisponibles = 295,
                            Duracion = "12 Hora(s)",
                            FechaLlegada = new DateTime(2023, 1, 25, 0, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 1, 2, 3, 0, 0, 514, DateTimeKind.Local),
                            Precio = 435000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 4
                        },
                        new
                        {
                            ViajeId = 21,
                            AsientosDisponibles = 133,
                            Duracion = "8 Hora(s)",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 11, 28, 9, 0, 0, 514, DateTimeKind.Local),
                            Precio = 130000,
                            TipoViaje = "Ida",
                            TransporteId = 5
                        },
                        new
                        {
                            ViajeId = 22,
                            AsientosDisponibles = 210,
                            Duracion = "1 Hora(s) 30min",
                            FechaLlegada = new DateTime(2023, 12, 10, 7, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 12, 3, 3, 0, 0, 514, DateTimeKind.Local),
                            Precio = 30000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 10
                        },
                        new
                        {
                            ViajeId = 23,
                            AsientosDisponibles = 300,
                            Duracion = "21 Hora(s)",
                            FechaLlegada = new DateTime(2024, 2, 7, 5, 30, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2024, 2, 1, 3, 30, 0, 514, DateTimeKind.Local),
                            Precio = 600000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 6
                        },
                        new
                        {
                            ViajeId = 24,
                            AsientosDisponibles = 275,
                            Duracion = "5 Horas",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 8, 25, 4, 0, 0, 514, DateTimeKind.Local),
                            Precio = 145000,
                            TipoViaje = "Ida",
                            TransporteId = 7
                        },
                        new
                        {
                            ViajeId = 25,
                            AsientosDisponibles = 300,
                            Duracion = "3 Horas 30 min",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 11, 8, 11, 30, 0, 514, DateTimeKind.Local),
                            Precio = 80500,
                            TipoViaje = "Ida",
                            TransporteId = 11
                        },
                        new
                        {
                            ViajeId = 26,
                            AsientosDisponibles = 300,
                            Duracion = "31 Horas 20 min",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 8, 25, 4, 0, 0, 514, DateTimeKind.Local),
                            Precio = 635000,
                            TipoViaje = "Ida",
                            TransporteId = 12
                        },
                        new
                        {
                            ViajeId = 27,
                            AsientosDisponibles = 250,
                            Duracion = "20 Horas 30 min",
                            FechaLlegada = new DateTime(2024, 4, 15, 2, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2024, 4, 8, 7, 30, 0, 514, DateTimeKind.Local),
                            Precio = 545000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 13
                        },
                        new
                        {
                            ViajeId = 28,
                            AsientosDisponibles = 300,
                            Duracion = "20 Horas",
                            FechaLlegada = new DateTime(2023, 10, 30, 17, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 10, 15, 12, 0, 0, 514, DateTimeKind.Local),
                            Precio = 500000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 14
                        },
                        new
                        {
                            ViajeId = 29,
                            AsientosDisponibles = 70,
                            Duracion = "21 Hora(s)",
                            FechaLlegada = new DateTime(2024, 1, 9, 0, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2024, 1, 2, 3, 0, 0, 514, DateTimeKind.Local),
                            Precio = 28000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 24
                        },
                        new
                        {
                            ViajeId = 30,
                            AsientosDisponibles = 73,
                            Duracion = "10 Hora(s)",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 11, 28, 9, 0, 0, 514, DateTimeKind.Local),
                            Precio = 238000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 23
                        },
                        new
                        {
                            ViajeId = 31,
                            AsientosDisponibles = 54,
                            Duracion = "4 horas",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 9, 3, 3, 0, 0, 514, DateTimeKind.Local),
                            Precio = 22000,
                            TipoViaje = "Ida",
                            TransporteId = 25
                        },
                        new
                        {
                            ViajeId = 32,
                            AsientosDisponibles = 50,
                            Duracion = "17 Hora(s)",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 10, 14, 3, 30, 0, 514, DateTimeKind.Local),
                            Precio = 41000,
                            TipoViaje = "Ida",
                            TransporteId = 26
                        },
                        new
                        {
                            ViajeId = 33,
                            AsientosDisponibles = 44,
                            Duracion = "3 Horas 30 min",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 8, 25, 4, 0, 0, 514, DateTimeKind.Local),
                            Precio = 26500,
                            TipoViaje = "Ida",
                            TransporteId = 27
                        },
                        new
                        {
                            ViajeId = 34,
                            AsientosDisponibles = 175,
                            Duracion = "4 Horas 30 min",
                            FechaLlegada = new DateTime(2023, 10, 2, 11, 30, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 9, 26, 11, 30, 0, 514, DateTimeKind.Local),
                            Precio = 20500,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 35
                        },
                        new
                        {
                            ViajeId = 35,
                            AsientosDisponibles = 250,
                            Duracion = "6 Horas",
                            FechaLlegada = new DateTime(2023, 12, 15, 2, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 12, 8, 7, 30, 0, 514, DateTimeKind.Local),
                            Precio = 15000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 36
                        },
                        new
                        {
                            ViajeId = 36,
                            AsientosDisponibles = 220,
                            Duracion = "7 Horas",
                            FechaLlegada = new DateTime(2023, 10, 22, 7, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 10, 15, 12, 0, 0, 514, DateTimeKind.Local),
                            Precio = 19000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 37
                        },
                        new
                        {
                            ViajeId = 37,
                            AsientosDisponibles = 220,
                            Duracion = "5 Hora(s) 30 min",
                            FechaLlegada = new DateTime(2024, 1, 9, 0, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2024, 1, 2, 3, 0, 0, 514, DateTimeKind.Local),
                            Precio = 15000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 38
                        },
                        new
                        {
                            ViajeId = 38,
                            AsientosDisponibles = 200,
                            Duracion = "8 Hora(s)",
                            FechaLlegada = new DateTime(2024, 1, 9, 0, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2024, 1, 2, 9, 0, 0, 514, DateTimeKind.Local),
                            Precio = 17000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 34
                        },
                        new
                        {
                            ViajeId = 39,
                            AsientosDisponibles = 200,
                            Duracion = "6 horas",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 9, 3, 3, 0, 0, 514, DateTimeKind.Local),
                            Precio = 22000,
                            TipoViaje = "Ida",
                            TransporteId = 36
                        },
                        new
                        {
                            ViajeId = 40,
                            AsientosDisponibles = 75,
                            Duracion = "6 Hora(s)",
                            FechaLlegada = new DateTime(2023, 10, 19, 3, 0, 0, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 10, 14, 3, 30, 0, 514, DateTimeKind.Local),
                            Precio = 23000,
                            TipoViaje = "Ida y vuelta",
                            TransporteId = 26
                        },
                        new
                        {
                            ViajeId = 41,
                            AsientosDisponibles = 75,
                            Duracion = "24 Hora(s)",
                            FechaLlegada = new DateTime(1111, 11, 11, 8, 11, 11, 514, DateTimeKind.Local),
                            FechaSalida = new DateTime(2023, 8, 25, 4, 0, 0, 514, DateTimeKind.Local),
                            Precio = 26500,
                            TipoViaje = "Ida",
                            TransporteId = 27
                        });
                });

            modelBuilder.Entity("Domain.Entities.Pasajero", b =>
                {
                    b.HasOne("Domain.Entities.Viaje", "Viaje")
                        .WithMany("Pasajeros")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Domain.Entities.Viaje", b =>
                {
                    b.Navigation("Pasajeros");
                });
#pragma warning restore 612, 618
        }
    }
}
